version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    # volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./html:/var/www/html