version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
