global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['https://grafana-test.mfzrl.cyou/']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['https://prometheus-test.mfzrl.cyou/']